language: node_js
node_js:
  - 10
services:
  - docker
env:
  - STATSD_HOST=localhost STATSD_PORT=8125 SOCKET_PORT=8000
before_install:
  - docker build -t ilguzin/statsd-socket.io-backend .
  - docker run -itd -p ${STATSD_PORT}:${STATSD_PORT}/udp -p ${SOCKET_PORT}:${SOCKET_PORT} ilguzin/statsd-socket.io-backend
  - docker ps -a
before_script:
  - npm ci
  - npm run build
script:
  - npm run test:ci
deploy:
  provider: npm
  email: "ilguzin@gmail.com"
  api_key: "NPM_AUTH_TOKEN"